# A TOML linter such as https://taplo.tamasfe.dev/ can use this schema to validate your config.
# If you encounter any issues, please make an issue at https://github.com/yazi-rs/schemas.
"$schema" = "https://yazi-rs.github.io/schemas/theme.json"

# vim:fileencoding=utf-8:foldmethod=marker

########## Manager ##########

[mgr]
cwd = { fg = "lightgreen" }

# Find
find_keyword  = { fg = "lightyellow", bold = true, italic = true, underline = true }
find_position = { fg = "gray", bg = "reset", bold = true, italic = true }

# Marker
marker_copied   = { fg = "lightgreen", bg = "lightgreen" }
marker_cut      = { fg = "lightred", bg = "lightred" }
marker_marked   = { fg = "lightcyan", bg = "lightcyan" }
marker_selected = { fg = "lightyellow", bg = "lightyellow" }

# Count
count_copied   = { fg = "darkgray", bg = "lightgreen" }
count_cut      = { fg = "darkgray", bg = "lightred" }
count_selected = { fg = "darkgray", bg = "lightyellow" }

# Border
border_symbol = "│"
border_style  = { fg = "gray" }

########## END Manager ##########


########## Tabs ##########

[tabs]
active   = { fg = "black", bg = "blue", bold = true }
inactive = { fg = "blue", bg = "darkgray" }

########## END Tabs ##########


########## Mode ##########

[mode]

normal_main = { fg = "black", bg = "lightblue", bold = true }
normal_alt  = { fg = "lightblue", bg = "darkgray" }

# Select mode
select_main = { fg = "black", bg = "lightcyan", bold = true }
select_alt  = { fg = "lightcyan", bg = "darkgray" }

# Unset mode
unset_main = { fg = "black", bg = "lightred", bold = true }
unset_alt  = { fg = "lightred", bg = "darkgray" }

########## END Mode ##########


########## Status bar ##########

[status]
# Permissions
perm_sep   = { fg = "gray" }
perm_type  = { fg = "blue" }
perm_read  = { fg = "lightyellow" }
perm_write = { fg = "red" }
perm_exec  = { fg = "green" }

# Progress
progress_label  = { fg = "white", bold = true }
progress_normal = { fg = "green", bg = "darkgray" }
progress_error  = { fg = "yellow", bg = "red" }

########## END Status bar ##########


########## Pick ##########

[pick]
border   = { fg = "blue" }
active   = { fg = "gray", bold = true }
inactive = {}

########## END Pick ##########


########## Input ##########

[input]
border   = { fg = "lightblue" }
title    = {}
value    = {}
selected = { reversed = true }

########## END Input ##########


########## Completion ##########

[cmp]
border = { fg = "lightblue" }

########## END Completion ##########


########## Tasks ##########

[tasks]
border  = { fg = "lightblue" }
title   = {}
hovered = { fg = "gray", bold = true }

########## END Tasks ##########


########## Which ##########

[which]
mask            = { bg = "darkgray" }
cand            = { fg = "red" }
rest            = { fg = "white" }
desc            = { fg = "white" }
separator       = "  "
separator_style = { fg = "lightyellow" }

########## END Which ##########


########## Help ##########

[help]
on      = { fg = "lightcyan" }
run     = { fg = "white" }
hovered = { reversed = true, bold = true }
footer  = { fg = "darkgray", bg = "white" }

########## END Help ##########


########## Spotter ##########

[spot]
border   = { fg = "blue" }
title    = { fg = "blue" }
tbl_col  = { fg = "lightcyan" }
tbl_cell = { fg = "white", bg = "darkgray" }

########## END Spotter ##########


########## Notification ##########

[notify]
title_info  = { fg = "green" }
title_warn  = { fg = "lightyellow" }
title_error = { fg = "red" }

########## END Notification ##########


########## File-specific styles ##########

[filetype]

rules = [
	# Image
	{ mime = "image/*", fg = "lightcyan" },
	# Media
	{ mime = "{audio,video}/*", fg = "lightyellow" },
	# Archive
	{ mime = "application/{zip,rar,7z*,tar,gzip,xz,zstd,bzip*,lzma,compress,archive,cpio,arj,xar,ms-cab*}", fg = "white" },
	# Document
	{ mime = "application/{pdf,doc,rtf}", fg = "green" },
	# Virtual file system
	{ mime = "vfs/{absent,stale}", fg = "gray" },
	# Fallback
	{ url = "*", fg = "white" },
	{ url = "*/", fg = "blue" },
]

[icon]
conds = [
	# Special files
	{ if = "orphan", text = "", fg = "white" },
	{ if = "link", text = "", fg = "gray" },
	{ if = "block", text = "", fg = "magenta" },
	{ if = "char", text = "", fg = "lightmagenta" },
	{ if = "fifo", text = "", fg = "green" },
	{ if = "sock", text = "", fg = "lightgreen" },
	{ if = "sticky", text = "", fg = "yellow" },
	{ if = "dummy", text = "", fg = "red" },

	# Fallback
	{ if = "dir", text = "", fg = "blue" },
	{ if = "exec", text = "", fg = "green" },
	{ if = "!dir", text = "", fg = "white" },
]

########## END File-specific styles ##########
